import { countryCodes } from "@/lib/countries";
import { getWorldRegion } from "@/lib/invoicing/regions";
import type { CountryInvoiceRule, TaxSystem, WorldRegion } from "@/lib/invoicing/types";

type CountryRuleOverride = Partial<Omit<CountryInvoiceRule, "country" | "region">>;

const VAT_REGIONS = new Set<WorldRegion>(["EUROPE", "AFRICA"]);
const GST_REGIONS = new Set<WorldRegion>(["OCEANIA"]);

const LIMITED_COUNTRIES = new Set(["BR", "CL", "CO", "GR", "HU", "IT", "MD", "MX", "MY", "PE", "RO", "SA"]);
const ADVANCED_COUNTRIES = new Set([
  "AL",
  "AE",
  "AG",
  "AX",
  "AM",
  "AD",
  "AT",
  "AW",
  "AU",
  "AZ",
  "BA",
  "BH",
  "BJ",
  "BE",
  "BB",
  "BG",
  "BS",
  "BZ",
  "BL",
  "BQ",
  "BW",
  "CA",
  "CI",
  "CM",
  "CV",
  "CW",
  "CY",
  "CZ",
  "CH",
  "DE",
  "DZ",
  "DK",
  "DM",
  "DO",
  "EG",
  "EE",
  "ES",
  "FJ",
  "FI",
  "FR",
  "FO",
  "GF",
  "GL",
  "GA",
  "GE",
  "GG",
  "GI",
  "GB",
  "GH",
  "GM",
  "GT",
  "GY",
  "HN",
  "HR",
  "IE",
  "IM",
  "IL",
  "IS",
  "IN",
  "ID",
  "JP",
  "JE",
  "JO",
  "KE",
  "KN",
  "KR",
  "KZ",
  "LC",
  "LB",
  "LI",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LK",
  "MC",
  "MF",
  "MQ",
  "MA",
  "MD",
  "MK",
  "MW",
  "MU",
  "MT",
  "NC",
  "NA",
  "NL",
  "NI",
  "NG",
  "NO",
  "NZ",
  "OM",
  "PG",
  "PF",
  "GP",
  "PH",
  "PR",
  "PM",
  "PL",
  "PT",
  "RW",
  "RS",
  "RU",
  "RE",
  "SC",
  "SE",
  "SG",
  "SI",
  "SK",
  "SL",
  "SN",
  "SM",
  "SR",
  "SX",
  "TN",
  "TH",
  "TR",
  "TT",
  "TF",
  "TZ",
  "UG",
  "UA",
  "US",
  "VA",
  "VC",
  "WF",
  "ZA",
  "ZM",
  "ZW",
  "YT",
]);

const COUNTRY_OVERRIDES: Record<string, CountryRuleOverride> = {
  AE: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  AW: {
    taxSystem: "SALES_TAX",
    taxLabel: "BBO/BAZV",
    requiresSellerTaxId: true,
  },
  AG: {
    taxSystem: "SALES_TAX",
    taxLabel: "ABST",
    requiresSellerTaxId: true,
  },
  AL: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  BD: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  AU: {
    taxSystem: "GST",
    taxLabel: "GST",
    requiresSellerTaxId: true,
  },
  AZ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  AM: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
  },
  AD: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  AX: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  AR: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  BO: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  CN: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  BB: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  BE: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  BH: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  BS: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  BL: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  BQ: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  BZ: {
    taxSystem: "SALES_TAX",
    taxLabel: "GST",
    requiresSellerTaxId: true,
  },
  BJ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  BW: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  BR: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: true,
    requiresLocalWarnings: true,
    requiresEInvoicing: true,
  },
  CA: {
    taxSystem: "GST",
    taxLabel: "GST/HST",
    requiresSellerTaxId: true,
  },
  CI: {
    taxSystem: "VAT",
    taxLabel: "TVA",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  CL: {
    taxSystem: "VAT",
    taxLabel: "VAT/IVA",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
    allowsReverseCharge: false,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  CO: {
    taxSystem: "VAT",
    taxLabel: "VAT/IVA",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
    allowsReverseCharge: false,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  CM: {
    taxSystem: "VAT",
    taxLabel: "TVA",
    requiresSellerTaxId: true,
  },
  CR: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  CW: {
    taxSystem: "SALES_TAX",
    taxLabel: "Omzetbelasting",
    requiresSellerTaxId: true,
  },
  CV: {
    taxSystem: "VAT",
    taxLabel: "IVA",
    requiresSellerTaxId: true,
  },
  DM: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  DZ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  DO: {
    taxSystem: "VAT",
    taxLabel: "ITBIS",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  EC: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  EG: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  GB: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  GH: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  FR: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  FO: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  GF: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  GL: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  GA: {
    taxSystem: "VAT",
    taxLabel: "TVA",
    requiresSellerTaxId: true,
  },
  FJ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  GE: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  GG: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  GI: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  GR: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  GT: {
    taxSystem: "VAT",
    taxLabel: "IVA",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  HK: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  GY: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  GM: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  HN: {
    taxSystem: "SALES_TAX",
    taxLabel: "ISV",
    requiresSellerTaxId: true,
  },
  HU: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  ID: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  IN: {
    taxSystem: "GST",
    taxLabel: "GST",
    requiresSellerTaxId: true,
    requiresLocalWarnings: true,
  },
  IM: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  IL: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  IT: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  JP: {
    taxSystem: "MIXED",
    taxLabel: "Consumption Tax",
    requiresSellerTaxId: true,
  },
  JE: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  JO: {
    taxSystem: "SALES_TAX",
    taxLabel: "Sales Tax",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  KE: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  KN: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  LB: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
  },
  LK: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
  },
  KH: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  KR: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  KZ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  LC: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  LR: {
    taxSystem: "GST",
    taxLabel: "GST",
    requiresSellerTaxId: true,
  },
  LS: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  MC: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  MF: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  MQ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  MD: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  MX: {
    taxSystem: "VAT",
    taxLabel: "VAT/IVA",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  MY: {
    taxSystem: "SALES_TAX",
    taxLabel: "SST",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  MN: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  MU: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  NC: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  MW: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  NA: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  NP: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  NZ: {
    taxSystem: "GST",
    taxLabel: "GST",
    requiresSellerTaxId: true,
  },
  NI: {
    taxSystem: "VAT",
    taxLabel: "IVA",
    requiresSellerTaxId: true,
  },
  NG: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  OM: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  PA: {
    taxSystem: "VAT",
    taxLabel: "ITBMS",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  PG: {
    taxSystem: "GST",
    taxLabel: "GST",
    requiresSellerTaxId: true,
  },
  PF: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  GP: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  PE: {
    taxSystem: "VAT",
    taxLabel: "IGV",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
    allowsReverseCharge: false,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  PK: {
    taxSystem: "SALES_TAX",
    taxLabel: "Sales Tax",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  PT: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  RU: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
  },
  SC: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  PH: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  PR: {
    taxSystem: "SALES_TAX",
    taxLabel: "IVU",
    requiresSellerTaxId: true,
  },
  PM: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  PL: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  PY: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  RO: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  RE: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  RW: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  RS: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  SA: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  SL: {
    taxSystem: "GST",
    taxLabel: "GST",
    requiresSellerTaxId: true,
  },
  SN: {
    taxSystem: "VAT",
    taxLabel: "TVA",
    requiresSellerTaxId: true,
  },
  SG: {
    taxSystem: "GST",
    taxLabel: "GST",
    requiresSellerTaxId: true,
  },
  SM: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  SR: {
    taxSystem: "VAT",
    taxLabel: "BTW",
    requiresSellerTaxId: true,
  },
  SX: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  SV: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  TN: {
    taxSystem: "VAT",
    taxLabel: "TVA",
    requiresSellerTaxId: true,
  },
  TH: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  TZ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  TR: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  TT: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  TF: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  UG: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  UA: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresBuyerTaxIdForB2B: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  UY: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  UZ: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  VC: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
  },
  WF: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  US: {
    taxSystem: "SALES_TAX",
    taxLabel: "Sales Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  TW: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  VA: {
    taxSystem: "MIXED",
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  },
  YT: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    allowsReverseCharge: true,
  },
  VN: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  ZM: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
  ZW: {
    taxSystem: "VAT",
    taxLabel: "VAT",
    requiresSellerTaxId: true,
    requiresEInvoicing: true,
    requiresLocalWarnings: true,
  },
};

const getRegionDefaults = (region: WorldRegion) => {
  if (VAT_REGIONS.has(region)) {
    return {
      taxSystem: "VAT" as TaxSystem,
      taxLabel: "VAT",
      requiresSellerTaxId: true,
      requiresBuyerTaxIdForB2B: true,
      allowsReverseCharge: true,
    };
  }
  if (GST_REGIONS.has(region)) {
    return {
      taxSystem: "GST" as TaxSystem,
      taxLabel: "GST",
      requiresSellerTaxId: true,
      requiresBuyerTaxIdForB2B: false,
      allowsReverseCharge: false,
    };
  }
  return {
    taxSystem: "MIXED" as TaxSystem,
    taxLabel: "Tax",
    requiresSellerTaxId: false,
    requiresBuyerTaxIdForB2B: false,
    allowsReverseCharge: false,
  };
};

export function getCountryInvoiceRule(countryCode?: string | null): CountryInvoiceRule | null {
  const country = String(countryCode || "").trim().toUpperCase();
  if (!country || !countryCodes.includes(country)) return null;

  const region = getWorldRegion(country);
  if (!region) return null;

  const defaults = getRegionDefaults(region);
  const override = COUNTRY_OVERRIDES[country] || {};
  const supportLevel = LIMITED_COUNTRIES.has(country)
    ? "LIMITED"
    : ADVANCED_COUNTRIES.has(country)
      ? "ADVANCED"
      : "STANDARD";

  return {
    country,
    region,
    supportLevel,
    taxSystem: defaults.taxSystem,
    taxLabel: defaults.taxLabel,
    requiresSellerTaxId: defaults.requiresSellerTaxId,
    requiresBuyerTaxIdForB2B: defaults.requiresBuyerTaxIdForB2B,
    allowsReverseCharge: defaults.allowsReverseCharge,
    requiresEInvoicing: false,
    requiresLocalWarnings: supportLevel === "LIMITED",
    ...override,
  };
}
