export type CountryDialCode = {
  code: string;
  dialCode: string;
};

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { code: "AF", dialCode: "93" },
  { code: "AL", dialCode: "355" },
  { code: "DZ", dialCode: "213" },
  { code: "AS", dialCode: "1" },
  { code: "AD", dialCode: "376" },
  { code: "AO", dialCode: "244" },
  { code: "AI", dialCode: "1" },
  { code: "AX", dialCode: "358" },
  { code: "AQ", dialCode: "672" },
  { code: "AG", dialCode: "1" },
  { code: "AR", dialCode: "54" },
  { code: "AM", dialCode: "374" },
  { code: "AW", dialCode: "297" },
  { code: "AU", dialCode: "61" },
  { code: "AT", dialCode: "43" },
  { code: "AZ", dialCode: "994" },
  { code: "BS", dialCode: "1" },
  { code: "BH", dialCode: "973" },
  { code: "BD", dialCode: "880" },
  { code: "BB", dialCode: "1" },
  { code: "BY", dialCode: "375" },
  { code: "BE", dialCode: "32" },
  { code: "BZ", dialCode: "501" },
  { code: "BJ", dialCode: "229" },
  { code: "BM", dialCode: "1" },
  { code: "BT", dialCode: "975" },
  { code: "BO", dialCode: "591" },
  { code: "BQ", dialCode: "599" },
  { code: "BA", dialCode: "387" },
  { code: "BW", dialCode: "267" },
  { code: "BV", dialCode: "47" },
  { code: "BR", dialCode: "55" },
  { code: "IO", dialCode: "246" },
  { code: "BN", dialCode: "673" },
  { code: "BG", dialCode: "359" },
  { code: "BF", dialCode: "226" },
  { code: "BI", dialCode: "257" },
  { code: "KH", dialCode: "855" },
  { code: "CM", dialCode: "237" },
  { code: "CA", dialCode: "1" },
  { code: "CV", dialCode: "238" },
  { code: "KY", dialCode: "1" },
  { code: "CF", dialCode: "236" },
  { code: "TD", dialCode: "235" },
  { code: "CL", dialCode: "56" },
  { code: "CN", dialCode: "86" },
  { code: "CX", dialCode: "61" },
  { code: "CC", dialCode: "61" },
  { code: "CO", dialCode: "57" },
  { code: "KM", dialCode: "269" },
  { code: "CG", dialCode: "242" },
  { code: "CD", dialCode: "243" },
  { code: "CK", dialCode: "682" },
  { code: "CR", dialCode: "506" },
  { code: "CI", dialCode: "225" },
  { code: "HR", dialCode: "385" },
  { code: "CU", dialCode: "53" },
  { code: "CW", dialCode: "599" },
  { code: "CY", dialCode: "357" },
  { code: "CZ", dialCode: "420" },
  { code: "DK", dialCode: "45" },
  { code: "DJ", dialCode: "253" },
  { code: "DM", dialCode: "1" },
  { code: "DO", dialCode: "1" },
  { code: "EC", dialCode: "593" },
  { code: "EG", dialCode: "20" },
  { code: "SV", dialCode: "503" },
  { code: "GQ", dialCode: "240" },
  { code: "ER", dialCode: "291" },
  { code: "EE", dialCode: "372" },
  { code: "ET", dialCode: "251" },
  { code: "FK", dialCode: "500" },
  { code: "FO", dialCode: "298" },
  { code: "FJ", dialCode: "679" },
  { code: "FI", dialCode: "358" },
  { code: "FR", dialCode: "33" },
  { code: "GF", dialCode: "594" },
  { code: "PF", dialCode: "689" },
  { code: "TF", dialCode: "262" },
  { code: "GA", dialCode: "241" },
  { code: "GM", dialCode: "220" },
  { code: "GE", dialCode: "995" },
  { code: "DE", dialCode: "49" },
  { code: "GH", dialCode: "233" },
  { code: "GI", dialCode: "350" },
  { code: "GR", dialCode: "30" },
  { code: "GL", dialCode: "299" },
  { code: "GD", dialCode: "1" },
  { code: "GP", dialCode: "590" },
  { code: "GS", dialCode: "500" },
  { code: "GU", dialCode: "1" },
  { code: "GT", dialCode: "502" },
  { code: "GG", dialCode: "44" },
  { code: "GN", dialCode: "224" },
  { code: "GW", dialCode: "245" },
  { code: "GY", dialCode: "592" },
  { code: "HT", dialCode: "509" },
  { code: "HN", dialCode: "504" },
  { code: "HK", dialCode: "852" },
  { code: "HM", dialCode: "672" },
  { code: "HU", dialCode: "36" },
  { code: "IS", dialCode: "354" },
  { code: "IN", dialCode: "91" },
  { code: "ID", dialCode: "62" },
  { code: "IR", dialCode: "98" },
  { code: "IQ", dialCode: "964" },
  { code: "IE", dialCode: "353" },
  { code: "IM", dialCode: "44" },
  { code: "IL", dialCode: "972" },
  { code: "IT", dialCode: "39" },
  { code: "JM", dialCode: "1" },
  { code: "JP", dialCode: "81" },
  { code: "JE", dialCode: "44" },
  { code: "JO", dialCode: "962" },
  { code: "KZ", dialCode: "7" },
  { code: "KE", dialCode: "254" },
  { code: "KI", dialCode: "686" },
  { code: "KP", dialCode: "850" },
  { code: "KR", dialCode: "82" },
  { code: "KW", dialCode: "965" },
  { code: "KG", dialCode: "996" },
  { code: "LA", dialCode: "856" },
  { code: "LV", dialCode: "371" },
  { code: "LB", dialCode: "961" },
  { code: "LS", dialCode: "266" },
  { code: "LR", dialCode: "231" },
  { code: "LY", dialCode: "218" },
  { code: "LI", dialCode: "423" },
  { code: "LT", dialCode: "370" },
  { code: "LU", dialCode: "352" },
  { code: "MO", dialCode: "853" },
  { code: "MK", dialCode: "389" },
  { code: "MG", dialCode: "261" },
  { code: "MW", dialCode: "265" },
  { code: "MY", dialCode: "60" },
  { code: "MV", dialCode: "960" },
  { code: "ML", dialCode: "223" },
  { code: "MT", dialCode: "356" },
  { code: "MH", dialCode: "692" },
  { code: "MQ", dialCode: "596" },
  { code: "MR", dialCode: "222" },
  { code: "MU", dialCode: "230" },
  { code: "YT", dialCode: "262" },
  { code: "MX", dialCode: "52" },
  { code: "FM", dialCode: "691" },
  { code: "MD", dialCode: "373" },
  { code: "MC", dialCode: "377" },
  { code: "MN", dialCode: "976" },
  { code: "ME", dialCode: "382" },
  { code: "MS", dialCode: "1" },
  { code: "MA", dialCode: "212" },
  { code: "MZ", dialCode: "258" },
  { code: "MM", dialCode: "95" },
  { code: "NA", dialCode: "264" },
  { code: "NR", dialCode: "674" },
  { code: "NP", dialCode: "977" },
  { code: "NL", dialCode: "31" },
  { code: "NC", dialCode: "687" },
  { code: "NZ", dialCode: "64" },
  { code: "PN", dialCode: "64" },
  { code: "NI", dialCode: "505" },
  { code: "NE", dialCode: "227" },
  { code: "NG", dialCode: "234" },
  { code: "NU", dialCode: "683" },
  { code: "NF", dialCode: "672" },
  { code: "MP", dialCode: "1" },
  { code: "NO", dialCode: "47" },
  { code: "OM", dialCode: "968" },
  { code: "PK", dialCode: "92" },
  { code: "PW", dialCode: "680" },
  { code: "PS", dialCode: "970" },
  { code: "PA", dialCode: "507" },
  { code: "PG", dialCode: "675" },
  { code: "PY", dialCode: "595" },
  { code: "PE", dialCode: "51" },
  { code: "PH", dialCode: "63" },
  { code: "PL", dialCode: "48" },
  { code: "PT", dialCode: "351" },
  { code: "PR", dialCode: "1" },
  { code: "QA", dialCode: "974" },
  { code: "RE", dialCode: "262" },
  { code: "RO", dialCode: "40" },
  { code: "RU", dialCode: "7" },
  { code: "RW", dialCode: "250" },
  { code: "BL", dialCode: "590" },
  { code: "SH", dialCode: "290" },
  { code: "KN", dialCode: "1" },
  { code: "LC", dialCode: "1" },
  { code: "MF", dialCode: "590" },
  { code: "PM", dialCode: "508" },
  { code: "VC", dialCode: "1" },
  { code: "WS", dialCode: "685" },
  { code: "SM", dialCode: "378" },
  { code: "ST", dialCode: "239" },
  { code: "SA", dialCode: "966" },
  { code: "SN", dialCode: "221" },
  { code: "RS", dialCode: "381" },
  { code: "SC", dialCode: "248" },
  { code: "SL", dialCode: "232" },
  { code: "SG", dialCode: "65" },
  { code: "SX", dialCode: "1" },
  { code: "SK", dialCode: "421" },
  { code: "SI", dialCode: "386" },
  { code: "SB", dialCode: "677" },
  { code: "SO", dialCode: "252" },
  { code: "ZA", dialCode: "27" },
  { code: "SS", dialCode: "211" },
  { code: "ES", dialCode: "34" },
  { code: "LK", dialCode: "94" },
  { code: "SD", dialCode: "249" },
  { code: "SR", dialCode: "597" },
  { code: "SJ", dialCode: "47" },
  { code: "SZ", dialCode: "268" },
  { code: "SE", dialCode: "46" },
  { code: "CH", dialCode: "41" },
  { code: "SY", dialCode: "963" },
  { code: "TW", dialCode: "886" },
  { code: "TJ", dialCode: "992" },
  { code: "TZ", dialCode: "255" },
  { code: "TH", dialCode: "66" },
  { code: "TL", dialCode: "670" },
  { code: "TG", dialCode: "228" },
  { code: "TK", dialCode: "690" },
  { code: "TO", dialCode: "676" },
  { code: "TT", dialCode: "1" },
  { code: "TN", dialCode: "216" },
  { code: "TR", dialCode: "90" },
  { code: "TM", dialCode: "993" },
  { code: "TC", dialCode: "1" },
  { code: "TV", dialCode: "688" },
  { code: "UG", dialCode: "256" },
  { code: "UA", dialCode: "380" },
  { code: "AE", dialCode: "971" },
  { code: "GB", dialCode: "44" },
  { code: "US", dialCode: "1" },
  { code: "UM", dialCode: "1" },
  { code: "UY", dialCode: "598" },
  { code: "UZ", dialCode: "998" },
  { code: "VU", dialCode: "678" },
  { code: "VA", dialCode: "379" },
  { code: "VE", dialCode: "58" },
  { code: "VN", dialCode: "84" },
  { code: "VG", dialCode: "1" },
  { code: "VI", dialCode: "1" },
  { code: "WF", dialCode: "681" },
  { code: "EH", dialCode: "212" },
  { code: "YE", dialCode: "967" },
  { code: "ZM", dialCode: "260" },
  { code: "ZW", dialCode: "263" },
  { code: "XK", dialCode: "383" },
];

export const countryCodes = COUNTRY_DIAL_CODES.map((entry) => entry.code);

const countryNames: Partial<Record<string, string>> = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AX: "\u00c5land Islands",
  AQ: "Antarctica",
  AG: "Antigua & Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BQ: "Caribbean Netherlands",
  BA: "Bosnia & Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo - Brazzaville",
  CD: "Congo - Kinshasa",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "C\u00f4te d\u2019Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Cura\u00e7ao",
  CY: "Cyprus",
  CZ: "Czechia",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GS: "South Georgia & South Sandwich Islands",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HK: "Hong Kong SAR China",
  HM: "Heard & McDonald Islands",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao SAR China",
  MK: "North Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar (Burma)",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  PN: "Pitcairn Islands",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territories",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "R\u00e9union",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  BL: "St. Barth\u00e9lemy",
  SH: "St. Helena",
  KN: "St. Kitts & Nevis",
  LC: "St. Lucia",
  MF: "St. Martin",
  PM: "St. Pierre & Miquelon",
  VC: "St. Vincent & Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "S\u00e3o Tom\u00e9 & Pr\u00edncipe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard & Jan Mayen",
  SZ: "Eswatini",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad & Tobago",
  TN: "Tunisia",
  TR: "T\u00fcrkiye",
  TM: "Turkmenistan",
  TC: "Turks & Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "U.S. Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VA: "Vatican City",
  VE: "Venezuela",
  VN: "Vietnam",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  WF: "Wallis & Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  XK: "Kosovo",
};

const dialCodesSorted = [...COUNTRY_DIAL_CODES].sort(
  (a, b) => b.dialCode.length - a.dialCode.length
);

export function getCountryFlag(code: string) {
  const normalized = String(code || "").toUpperCase();
  if (normalized.length !== 2) return "";
  const first = 127397 + normalized.charCodeAt(0);
  const second = 127397 + normalized.charCodeAt(1);
  return String.fromCodePoint(first, second);
}

export function getCountryName(code: string, locale = "en") {
  const normalized = String(code || "").toUpperCase();
  const staticName = countryNames[normalized];
  if (staticName) return staticName;
  try {
    const displayNames = new Intl.DisplayNames([locale || "en"], { type: "region" });
    return displayNames.of(normalized) || normalized;
  } catch {
    return normalized;
  }
}

export function getDialCode(code: string) {
  const normalized = String(code || "").toUpperCase();
  const entry = COUNTRY_DIAL_CODES.find((item) => item.code === normalized);
  return entry?.dialCode || "";
}

export function parseE164(value: string | null | undefined) {
  const digits = String(value || "").replace(/\D/g, "");
  if (!digits) return null;
  for (const entry of dialCodesSorted) {
    if (digits.startsWith(entry.dialCode)) {
      return {
        code: entry.code,
        dialCode: entry.dialCode,
        nationalNumber: digits.slice(entry.dialCode.length),
      };
    }
  }
  return null;
}
