export const INVOICE_TOTALS_LABEL_WIDTH = 60;
export const INVOICE_TOTALS_VALUE_WIDTH = 150;
export const INVOICE_TOTALS_GAP = 4;
export const INVOICE_TOTALS_MAX_WIDTH =
  INVOICE_TOTALS_LABEL_WIDTH + INVOICE_TOTALS_VALUE_WIDTH + INVOICE_TOTALS_GAP;
