"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import useSWR from "swr";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

const DOCUMENT_OPTIONS = [
  { value: "subscription_receipt", label: "Subscription Receipt" },
  { value: "customer_invoice", label: "Customer Invoice" },
  { value: "payment_receipt", label: "Payment Receipt" },
] as const;

const PREVIEW_MODES = [
  { value: "template", label: "Template Layout" },
  { value: "real", label: "Real Transaction Example" },
] as const;

type DocumentType = (typeof DOCUMENT_OPTIONS)[number]["value"];
type PreviewMode = (typeof PREVIEW_MODES)[number]["value"];
type ExampleItem = { id: string; label: string };
type ExamplesResponse = { items: ExampleItem[] };

const fetcher = async <T,>(url: string): Promise<T> => {
  const response = await fetch(url, { cache: "no-store" });
  const json = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(String((json as { error?: string }).error || `Request failed (${response.status})`));
  }
  return json as T;
};

const buildPreviewUrl = (input: {
  type: DocumentType;
  mode: PreviewMode;
  exampleId?: string;
  download?: boolean;
}) => {
  const params = new URLSearchParams({
    type: input.type,
    mode: input.mode,
  });
  if (input.mode === "real" && input.exampleId) {
    params.set("id", input.exampleId);
  }
  if (input.download) {
    params.set("download", "1");
  }
  return `/api/admin/receipt-preview/document?${params.toString()}`;
};

export default function ReceiptPreviewClient() {
  const [documentType, setDocumentType] = useState<DocumentType>("subscription_receipt");
  const [mode, setMode] = useState<PreviewMode>("template");
  const [selectedExampleId, setSelectedExampleId] = useState("");
  const [iframeFailed, setIframeFailed] = useState(false);
  const previewFrameRef = useRef<HTMLIFrameElement | null>(null);

  const shouldLoadExamples = mode === "real";
  const {
    data: examplesResponse,
    error: examplesError,
    isLoading: examplesLoading,
  } = useSWR<ExamplesResponse>(
    shouldLoadExamples ? `/api/admin/receipt-preview/examples?type=${documentType}` : null,
    fetcher
  );

  const examples = useMemo(() => examplesResponse?.items ?? [], [examplesResponse?.items]);

  useEffect(() => {
    if (mode !== "real") {
      setSelectedExampleId("");
      return;
    }
    if (!examples.length) {
      setSelectedExampleId("");
      return;
    }
    if (!selectedExampleId || !examples.some((item) => item.id === selectedExampleId)) {
      setSelectedExampleId(examples[0].id);
    }
  }, [examples, mode, selectedExampleId]);

  useEffect(() => {
    setIframeFailed(false);
  }, [documentType, mode, selectedExampleId]);

  const canRenderPreview = mode === "template" || Boolean(selectedExampleId);
  const previewUrl = useMemo(
    () =>
      buildPreviewUrl({
        type: documentType,
        mode,
        exampleId: selectedExampleId,
      }),
    [documentType, mode, selectedExampleId]
  );
  const downloadUrl = useMemo(
    () =>
      buildPreviewUrl({
        type: documentType,
        mode,
        exampleId: selectedExampleId,
        download: true,
      }),
    [documentType, mode, selectedExampleId]
  );

  const openPreview = () => {
    if (!canRenderPreview) return;
    window.open(previewUrl, "_blank", "noopener,noreferrer");
  };

  const downloadPreview = () => {
    if (!canRenderPreview) return;
    window.open(downloadUrl, "_blank", "noopener,noreferrer");
  };

  const handleFrameLoad = () => {
    const frame = previewFrameRef.current;
    if (!frame) return;
    try {
      const href = frame.contentWindow?.location?.href || "";
      if (
        href.startsWith("about:neterror") ||
        href.startsWith("about:blank") ||
        href.startsWith("moz-extension://") ||
        href.includes("blocked")
      ) {
        setIframeFailed(true);
      }
    } catch {
      // Browsers can switch to an internal error document that is not accessible.
      setIframeFailed(true);
    }
  };

  return (
    <div className="space-y-5">
      <header className="space-y-1">
        <h1 className="text-3xl font-semibold text-foreground">Document Templates</h1>
        <p className="text-sm text-muted-foreground">Preview financial documents generated by the platform.</p>
      </header>

      <Card className="space-y-4 p-4">
        <div
          className={`grid gap-3 ${
            mode === "real" ? "lg:grid-cols-3" : "lg:grid-cols-2"
          }`}
        >
          <label className="grid min-w-0 gap-1">
            <span className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Document Type</span>
            <select
              value={documentType}
              onChange={(event) => setDocumentType(event.target.value as DocumentType)}
              className="h-10 w-full min-w-0 rounded-md border border-border/70 bg-background px-3 pr-8 text-sm"
            >
              {DOCUMENT_OPTIONS.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </label>

          <label className="grid min-w-0 gap-1">
            <span className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Preview Mode</span>
            <div className="flex h-10 w-full min-w-0 items-center rounded-md border border-border/70 bg-background p-1">
              {PREVIEW_MODES.map((option) => (
                <button
                  key={option.value}
                  type="button"
                  onClick={() => setMode(option.value)}
                  className={`rounded px-3 py-1 text-sm transition ${
                    mode === option.value
                      ? "bg-indigo-600 text-white"
                      : "text-muted-foreground hover:bg-muted/60"
                  }`}
                >
                  {option.label}
                </button>
              ))}
            </div>
          </label>

          {mode === "real" ? (
            <label className="grid min-w-0 gap-1">
              <span className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
                Example Document
              </span>
              <select
                value={selectedExampleId}
                onChange={(event) => setSelectedExampleId(event.target.value)}
                disabled={examplesLoading || examples.length === 0}
                className="h-10 w-full min-w-0 rounded-md border border-border/70 bg-background px-3 pr-8 text-sm disabled:cursor-not-allowed disabled:opacity-60"
              >
                {examplesLoading ? <option value="">Loading examples...</option> : null}
                {!examplesLoading && !examples.length ? <option value="">No documents available</option> : null}
                {examples.length
                  ? examples.map((example) => (
                      <option key={example.id} value={example.id}>
                        {example.label}
                      </option>
                    ))
                  : null}
              </select>
            </label>
          ) : null}

        </div>

        {examplesError ? <Alert variant="error">{examplesError.message}</Alert> : null}

        <div className="flex flex-col gap-2 border-t border-border/70 pt-3 sm:flex-row sm:items-center sm:justify-end">
          <Button
            size="sm"
            onClick={openPreview}
            disabled={!canRenderPreview}
            className="w-full sm:w-auto"
          >
            Open Preview
          </Button>
          <Button
            size="sm"
            variant="secondary"
            onClick={downloadPreview}
            disabled={!canRenderPreview}
            className="w-full sm:w-auto"
          >
            Download PDF
          </Button>
        </div>
      </Card>

      <Card className="space-y-3 p-4">
        <p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Template Preview</p>

        {!canRenderPreview ? (
          <div className="rounded-lg border border-dashed border-border/70 px-4 py-10 text-center text-sm text-muted-foreground">
            Select an example document to render a real preview.
          </div>
        ) : iframeFailed ? (
          <div className="space-y-3 rounded-lg border border-border/70 bg-muted/20 p-4">
            <div className="flex h-52 items-center justify-center rounded-lg border border-dashed border-border/70 bg-background text-sm text-muted-foreground">
              PDF Document Placeholder
            </div>
            <p className="text-sm text-muted-foreground">
              PDF preview is not embedded due to browser security restrictions.
            </p>
            <div className="flex flex-wrap gap-2">
              <Button size="sm" onClick={openPreview}>
                Open PDF in new tab
              </Button>
              <Button size="sm" variant="secondary" onClick={downloadPreview}>
                Download PDF
              </Button>
            </div>
          </div>
        ) : (
          <iframe
            ref={previewFrameRef}
            title="Receipt preview"
            src={previewUrl}
            className="h-[760px] w-full rounded-lg border border-border/70 bg-background"
            onLoad={handleFrameLoad}
            onError={() => setIframeFailed(true)}
          />
        )}
      </Card>
    </div>
  );
}
