import type { EInvoiceCompletionStage, EInvoiceProviderKey } from "@/lib/einvoicing/types";
import { plannedProviderEntries } from "@/lib/einvoicing/planned-provider-registry";

export type EInvoiceProviderField = {
  key: string;
  label: string;
  secret?: boolean;
  required?: boolean;
  placeholder?: string;
  helpText?: string;
};

export type EInvoiceProviderDefinition = {
  key: EInvoiceProviderKey;
  displayName: string;
  countryCodes: string[];
  liveSubmissionAvailable: boolean;
  supportsStatusSync: boolean;
  credentialFields: EInvoiceProviderField[];
  completionStage: EInvoiceCompletionStage;
  capabilitySummary?: string;
};

const providerEntries = [
  ["MYINVOIS", { key: "MYINVOIS", displayName: "MyInvois", countryCodes: ["MY"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live auth, submission, status sync, and cancellation are wired for MyInvois. Production readiness depends on a validated non-sandbox connection with client credentials and any required on-behalf-of delegation configured.", credentialFields: [{ key: "clientId", label: "Client ID", required: true }, { key: "clientSecret", label: "Client secret", required: true, secret: true }, { key: "scope", label: "Scope", placeholder: "InvoicingAPI" }, { key: "onBehalfOf", label: "On-behalf-of TIN" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["RO_EFACTURA", { key: "RO_EFACTURA", displayName: "RO e-Factura", countryCodes: ["RO"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "OAuth, UBL upload, status sync, and cancellation are wired for RO e-Factura. Production readiness now depends on a validated non-sandbox connection with ANAF credentials and cancellation endpoint configured.", credentialFields: [{ key: "clientId", label: "Client ID", required: true }, { key: "clientSecret", label: "Client secret", required: true, secret: true }, { key: "redirectUri", label: "Redirect URI", required: true }, { key: "refreshToken", label: "Refresh token", required: true, secret: true }, { key: "cif", label: "Seller CIF" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["MYDATA", { key: "MYDATA", displayName: "myDATA", countryCodes: ["GR"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Submission, status sync, and cancellation are wired for myDATA. Production readiness depends on a validated non-sandbox AADE connection with taxpayer credentials configured.", credentialFields: [{ key: "aadeUserId", label: "AADE user ID", required: true }, { key: "subscriptionKey", label: "Subscription key", required: true, secret: true }, { key: "entityVatNumber", label: "Entity VAT number" }, { key: "baseUrl", label: "API base URL override" }] }],
  ["ZATCA", { key: "ZATCA", displayName: "ZATCA", countryCodes: ["SA"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live submission, status sync, and cancellation are wired for ZATCA. Production readiness depends on a validated non-sandbox connection with onboarding, signing, and operational artifacts configured.", credentialFields: [{ key: "tin", label: "TIN", required: true }, { key: "portalUsername", label: "ERAD username" }, { key: "portalPassword", label: "ERAD password", secret: true }, { key: "otp", label: "OTP", secret: true }, { key: "csr", label: "CSR", secret: true }, { key: "csid", label: "CSID", secret: true }, { key: "privateKeyPem", label: "Private key", secret: true }, { key: "certificatePem", label: "Certificate", secret: true }, { key: "binarySecurityToken", label: "Binary security token", secret: true }, { key: "binarySecurityTokenSecret", label: "Binary token secret", secret: true }, { key: "complianceRequestId", label: "Compliance request ID" }, { key: "egsSerialNumber", label: "EGS serial number" }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["IT_SDI", { key: "IT_SDI", displayName: "SdI", countryCodes: ["IT"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live submission, status sync, and cancellation are wired for SdI. Production readiness depends on a validated non-sandbox connection with accredited routing, signing material, and endpoint configuration.", credentialFields: [{ key: "vatNumber", label: "VAT number", required: true }, { key: "transmissionId", label: "Transmission ID" }, { key: "recipientCode", label: "Recipient code" }, { key: "pecEmail", label: "PEC email" }, { key: "certificatePem", label: "Certificate", secret: true }, { key: "privateKeyPem", label: "Private key", secret: true }, { key: "submissionUrl", label: "Submission URL", required: true }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["MX_CFDI", { key: "MX_CFDI", displayName: "CFDI", countryCodes: ["MX"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live PAC submission, status sync, and cancellation are wired for CFDI. Production readiness depends on a validated non-sandbox connection with RFC, CSD signing material, and PAC endpoints configured.", credentialFields: [{ key: "rfc", label: "RFC", required: true }, { key: "ciec", label: "CIEC", secret: true }, { key: "csdCertificatePem", label: "CSD certificate", secret: true }, { key: "csdPrivateKeyPem", label: "CSD private key", secret: true }, { key: "csdPrivateKeyPassword", label: "CSD key password", secret: true }, { key: "pacUrl", label: "PAC URL", required: true }, { key: "pacStatusUrl", label: "PAC status URL" }, { key: "pacCancelUrl", label: "PAC cancellation URL" }] }],
  ["BR_NFE", { key: "BR_NFE", displayName: "NF-e", countryCodes: ["BR"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live SEFAZ submission, status sync, and cancellation are wired for NF-e. Production readiness depends on a validated non-sandbox connection with issuer CNPJ, UF, signing material, and transport endpoints configured.", credentialFields: [{ key: "cnpj", label: "CNPJ", required: true }, { key: "certificatePem", label: "Certificate", required: true, secret: true }, { key: "privateKeyPem", label: "Private key", required: true, secret: true }, { key: "certificatePassword", label: "Certificate password", secret: true }, { key: "uf", label: "UF", required: true }, { key: "submissionUrl", label: "Submission URL", required: true }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["CL_DTE", { key: "CL_DTE", displayName: "DTE", countryCodes: ["CL"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live SII submission, status sync, and cancellation are wired for DTE. Production readiness depends on a validated non-sandbox connection with issuer RUT, SII credentials, signing material, and transport endpoints configured.", credentialFields: [{ key: "rut", label: "RUT", required: true }, { key: "certificatePem", label: "Certificate", required: true, secret: true }, { key: "privateKeyPem", label: "Private key", required: true, secret: true }, { key: "siiUser", label: "SII user", required: true }, { key: "siiPassword", label: "SII password", required: true, secret: true }, { key: "submissionUrl", label: "Submission URL", required: true }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["CO_DIAN", { key: "CO_DIAN", displayName: "DIAN", countryCodes: ["CO"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live DIAN submission, status sync, and cancellation are wired for DIAN. Production readiness depends on a validated non-sandbox connection with NIT, software credentials, signing material, and transport endpoints configured.", credentialFields: [{ key: "nit", label: "NIT", required: true }, { key: "softwareId", label: "Software ID", required: true }, { key: "softwarePin", label: "Software PIN", required: true, secret: true }, { key: "certificatePem", label: "Certificate", required: true, secret: true }, { key: "privateKeyPem", label: "Private key", required: true, secret: true }, { key: "submissionUrl", label: "Submission URL", required: true }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["PE_SUNAT", { key: "PE_SUNAT", displayName: "SUNAT", countryCodes: ["PE"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live SUNAT submission, status sync, and cancellation are wired for SUNAT. Production readiness depends on a validated non-sandbox connection with RUC, SOL credentials, signing material, and transport endpoints configured.", credentialFields: [{ key: "ruc", label: "RUC", required: true }, { key: "solUser", label: "SOL user", required: true }, { key: "solPassword", label: "SOL password", required: true, secret: true }, { key: "certificatePem", label: "Certificate", required: true, secret: true }, { key: "privateKeyPem", label: "Private key", required: true, secret: true }, { key: "submissionUrl", label: "Submission URL", required: true }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["HU_NAV", { key: "HU_NAV", displayName: "NAV Online Invoice", countryCodes: ["HU"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live NAV reporting, status sync, and cancellation are wired for NAV Online Invoice. Production readiness depends on a validated non-sandbox connection with tax number, technical-user credentials, signing keys, and transport endpoints configured.", credentialFields: [{ key: "taxNumber", label: "Tax number", required: true }, { key: "technicalUserName", label: "Technical user", required: true }, { key: "technicalUserPassword", label: "Technical user password", required: true, secret: true }, { key: "signingKey", label: "Signing key", required: true, secret: true }, { key: "exchangeKey", label: "Exchange key", required: true, secret: true }, { key: "submissionUrl", label: "Submission URL", required: true }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ["MD_EFACTURA", { key: "MD_EFACTURA", displayName: "e-Factura", countryCodes: ["MD"], liveSubmissionAvailable: true, supportsStatusSync: true, completionStage: "PRODUCTION_READY", capabilitySummary: "Live Moldova e-Factura submission, status sync, and cancellation are wired. Production readiness depends on a validated non-sandbox connection with taxpayer code, SFS credentials, signing material, and transport endpoints configured.", credentialFields: [{ key: "taxpayerCode", label: "Taxpayer code", required: true }, { key: "username", label: "Username", required: true }, { key: "password", label: "Password", required: true, secret: true }, { key: "certificatePem", label: "Certificate", required: true, secret: true }, { key: "privateKeyPem", label: "Private key", required: true, secret: true }, { key: "submissionUrl", label: "Submission URL", required: true }, { key: "statusUrl", label: "Status URL" }, { key: "cancelUrl", label: "Cancellation URL" }] }],
  ...plannedProviderEntries,
] as const satisfies readonly [EInvoiceProviderKey, EInvoiceProviderDefinition][];

const PROVIDER_REGISTRY = Object.fromEntries(providerEntries) as Record<EInvoiceProviderKey, EInvoiceProviderDefinition>;

export function getEInvoiceProviderDefinition(key?: string | null) {
  const normalized = String(key || "").trim().toUpperCase() as EInvoiceProviderKey;
  return PROVIDER_REGISTRY[normalized] || null;
}

export function listEInvoiceProviderDefinitions() {
  return Object.values(PROVIDER_REGISTRY);
}
