import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { resolveInvoicePublicLink } from "@/lib/invoice-public-link";
import {
  calculateTotalsFromAmounts,
  normalizeInvoiceItems,
  resolveInvoiceCustomer,
  getBusinessLogoDataUrl,
} from "@/lib/invoice";
import { isAllowedCurrency, normalizeCurrency } from "@/lib/payments/currency-allowlist";
import { InvoicePreview } from "@/components/invoices/invoice-preview";
import { normalizeVatSettings } from "@/lib/vat";

export const dynamic = "force-dynamic";

type PageProps = {
  params: { token: string };
  searchParams?: Record<string, string | string[] | undefined>;
};

const isPayableStatus = (status: string) => ["SENT", "OVERDUE", "FAILED"].includes(status);
const isFinalStatus = (status: string) => ["PAID", "CANCELED", "EXPIRED"].includes(status);

export default async function PublicInvoicePage({ params, searchParams }: PageProps) {
  const resolvedParams = await Promise.resolve(params);
  const resolvedSearchParams = await Promise.resolve(searchParams);
  const rawToken = resolvedParams?.token;
  const token = typeof rawToken === "string" ? rawToken.trim() : "";
  if (!token) notFound();

  const link = await resolveInvoicePublicLink(token);
  if (!link?.invoice) notFound();

  const invoice = link.invoice;
  const metadata = (invoice.metadata as any) || {};
  const customer = resolveInvoiceCustomer(metadata);
  const note = typeof metadata?.note === "string" ? metadata.note : null;
  const businessSnapshot = metadata.businessProfile || null;
  const business =
    businessSnapshot ||
    (await prisma.businessProfile.findUnique({
      where: { userId: invoice.userId },
      select: {
        businessName: true,
        businessEmail: true,
        businessPhone: true,
        businessAddress: true,
        taxId: true,
        vatEnabled: true,
        vatRate: true,
        vatPricingMode: true,
      },
    }));

  const normalizedCurrency = normalizeCurrency(invoice.currency || business?.defaultCurrency || "USD");
  if (!isAllowedCurrency(normalizedCurrency)) {
    return (
      <div className="mx-auto max-w-3xl px-6 py-12">
        <div className="rounded-2xl border border-border bg-card p-6 text-sm text-foreground">
          This invoice has an unsupported currency. Please contact the sender.
        </div>
      </div>
    );
  }

  const dueDateRaw = metadata?.dueDate ? new Date(metadata.dueDate) : null;
  const dueDate = dueDateRaw && !Number.isNaN(dueDateRaw.getTime()) ? dueDateRaw : null;

  const items = normalizeInvoiceItems(invoice.items);
  const vatSettings = normalizeVatSettings({
    enabled: business?.vatEnabled ?? false,
    rate: business?.vatRate ? Number(business.vatRate) : 0,
    mode:
      String(business?.vatPricingMode || "EXCLUSIVE").toLowerCase() === "inclusive"
        ? "inclusive"
        : "exclusive",
  });
  const totals = calculateTotalsFromAmounts(items, vatSettings, Number(invoice.discount || 0));

  const payable = isPayableStatus(invoice.status) && !link.usedAt && !isFinalStatus(invoice.status);
  const paymentLink = payable ? `/api/invoice/pay/${encodeURIComponent(token)}` : null;
  const logoDataUrl = getBusinessLogoDataUrl(invoice.userId || "");

  return (
    <div className="mx-auto max-w-5xl px-6 py-12">
      <InvoicePreview
        invoiceNumber={invoice.invoiceNumber}
        status={invoice.status}
        issuedAt={invoice.generatedAt}
        dueDate={dueDate}
        currency={normalizedCurrency}
        items={items}
        totals={totals}
        paymentLink={paymentLink}
        logoDataUrl={logoDataUrl}
        business={{
          businessName: business?.businessName || "Business",
          businessEmail: business?.businessEmail,
          businessAddress: business?.businessAddress,
          businessPhone: business?.businessPhone,
          taxId: business?.taxId,
        }}
        billTo={customer}
        note={note}
      />

      {resolvedSearchParams?.status === "paid" ? (
        <div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">
          Payment confirmed. Thank you!
        </div>
      ) : null}
      {resolvedSearchParams?.status === "failed" ? (
        <div className="mt-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
          Payment could not be confirmed. Please try again or contact the sender.
        </div>
      ) : null}

      <div className="mt-8 text-center text-xs text-muted-foreground">
        <div>This invoice was generated by Maboria.</div>
        <div>
          <Link href="https://www.maboria.com" className="underline">
            www.maboria.com
          </Link>
        </div>
      </div>
    </div>
  );
}
